FROM node:boron

# Create app directory
WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 8080

# Define command to start server
CMD [ "npm", "start" ]
